"""Your migration message

Revision ID: 021a43775b0b
Revises: 
Create Date: 2024-05-13 14:23:01.221568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021a43775b0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
