"""Update DBs

Revision ID: e3c53755dfc6
Revises: 21f356d7b073
Create Date: 2024-05-13 15:13:27.635259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c53755dfc6'
down_revision = '21f356d7b073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'purchase_event', ['purchase_event_id'], ['id'])

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'purchase_event', ['purchase_event_id'], ['id'])

    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchase_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'delivery_order', ['delivery_order_id'], ['id'])
        batch_op.create_foreign_key(None, 'purchase_order', ['purchase_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_order_id')
        batch_op.drop_column('delivery_order_id')

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_event_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_event_id')

    # ### end Alembic commands ###
